### ISSUE TITLE
[question] should worker suspend do restart? 

### ISSUE THREAD

**Issue by AmirGoldental** [AmirGoldental/MatlabRedisCluster#70]
Otherwise, the suspend only starts after the task ends

**Comment by AmirGoldental** [comment]
we can use the 'force' arg

**Comment by BambaDamba** [comment]
I guess we want the two kind of suspends, one is forced and with a restart (called suspend) and the other is drain (do not take any other jobs)

**Comment by BambaDamba** [comment]
closed via [a16a9d7](https://github.com/AmirGoldental/MatlabRedisCluster/commit/a16a9d7ed515e4ac5b8270d7764363bc3af2137b)
