### ISSUE TITLE
[question] how to manage a worker restart

### ISSUE THREAD

**Issue by AmirGoldental** [AmirGoldental/MatlabRedisCluster#73]
currently: kill -> start new worker  
gets a different key  
not sure this is optimal  
  
we can somehow reuse the input to mrc.join_as_worker and add input to the start worker bat  
If we are doing this, it is a good idea to add an option --suspended and then suspend will restart with --suspended (#70)

**Comment by BambaDamba** [comment]
The following logic is proposed for the watcher behavior:
- when matlab active and status is active -> wait
- when matlab dead and status is active -> change status to dead\restart (depends on crash policy)
- when matlab alive and status is restart -> kill matlab
- when matlab dead and status is restart -> start matlab and change status to active
- when matlab active and status is suspend -> kill matlab
- when matlab dead and status is suspend -> wait
- when matlab alive and status dead -> kill matlab
- when matlab dead and status dead -> exit

**Comment by BambaDamba** [comment]
closed via [a16a9d7](https://github.com/AmirGoldental/MatlabRedisCluster/commit/a16a9d7ed515e4ac5b8270d7764363bc3af2137b)
