### ISSUE TITLE
oops, I think I broke the "service" option

### ISSUE THREAD

**Issue by AmirGoldental** [AmirGoldental/MatlabRedisCluster#76]
with commit https://github.com/AmirGoldental/MatlabRedisCluster/commit/1501decf211e2ff18e11e9fde69445680891f1a9
can we solve this nicely?

**Comment by BambaDamba** [comment]
You can change title of cmd with title command, no need for starting a new process via start

**Comment by AmirGoldental** [comment]
What the commit tried to fix was to close the .bat window when the server is stopped using
mrc.redis_cmd('SHUTDOWN NOSAVE')
